### ISSUE TITLE
MarcProfiling job should more gracefully handle MARC parse errors

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#486]
It's possible to upload a file that looks like MARCXML or MARC binary but cannot be successfully parsed/analyzed as MARC. This causes the MarcProfiling job to get stuck in a fail/retry loop in sidekiq. Causes include files that look like marc binary but are malformed in some way.

Example error:

```
2022-03-17T14:33:44.171Z pid=97905 tid=2azx WARN: NoMethodError: undefined method `pack' for nil:NilClass
2022-03-17T14:33:44.171Z pid=97905 tid=2azx WARN: /Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:364:in `block in decode'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:339:in `upto'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:339:in `decode'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:283:in `decode'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:233:in `block in each'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:273:in `each_raw'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:232:in `each'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:90:in `each_with_index'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:90:in `each_raw_record'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:102:in `each'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:102:in `each'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:102:in `each'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:102:in `each_combined_record'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:80:in `block in each'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:196:in `block (2 levels) in with_reader'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:275:in `with_honeybadger_context'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:195:in `block in with_reader'
```

**Comment by corylown** [comment]
I'm thinking maybe this should fail, which raises a couple of other issues:

- How to update the JobTracker when a job is in a retry loop?
- How to update the JobTracker when a job is dead?
- How many times should a failed job retry before giving up?

**Comment by corylown** [comment]
I think this is mostly covered by fixing the job tracker design: https://github.com/pod4lib/aggregator/issues/317
