### ISSUE TITLE
Princeton: MarcProfilingJob failed on normalized full dump

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#507]
<img width="1227" alt="Screen Shot 2022-03-24 at 12 07 21 PM" src="https://user-images.githubusercontent.com/458247/159960191-4dcea25f-7144-43c4-9c10-f262c065b823.png">

```
[#<Sidekiq::SortedEntry:0x0000000007b34f00
  @args=nil,
  @item=
   {"retry"=>true,
    "queue"=>"default",
    "class"=>"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",
    "wrapped"=>"MarcProfilingJob",
    "args"=>
     [{"job_class"=>"MarcProfilingJob",
       "job_id"=>"ceb86f9e-b69e-47a9-9276-a5ec8fbea562",
       "provider_job_id"=>nil,
       "queue_name"=>"default",
       "priority"=>nil,
       "arguments"=>
        [{"_aj_globalid"=>"gid://aggregator/ActiveStorage::Blob/24606"},
         {"count"=>6601733, "_aj_ruby2_keywords"=>["count"]}],
       "executions"=>0,
       "exception_executions"=>{},
       "locale"=>"en",
       "timezone"=>"UTC",
       "enqueued_at"=>"2021-10-28T22:04:54Z"}],
    "jid"=>"54e4350f9c35e6869107c030",
    "created_at"=>1635458694.3732765,
    "enqueued_at"=>1637374253.5711856,
    "error_message"=>"undefined method `pack' for nil:NilClass",
    "error_class"=>"NoMethodError",
    "failed_at"=>1635462070.8818843,
    "retry_count"=>25,
    "retried_at"=>1637377445.9415011},
  @parent=#<Sidekiq::DeadSet:0x0000000007784658 @_size=202, @name="dead">,
  @queue="default",
  @score=1637377445.9418817,
  @value=
   "{\"retry\":true,\"queue\":\"default\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"MarcProfilingJob\",\"args\":[{\"job_class\":\"MarcProfilingJob\",\"job_id\":\"ceb86f9e-b69e-47a9-9276-a5ec8fbea562\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://aggregator/ActiveStorage::Blob/24606\"},{\"count\":6601733,\"_aj_ruby2_keywords\":[\"count\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2021-10-28T22:04:54Z\"}],\"jid\":\"54e4350f9c35e6869107c030\",\"created_at\":1635458694.3732765,\"enqueued_at\":1637374253.5711856,\"error_message\":\"undefined method `pack' for nil:NilClass\",\"error_class\":\"NoMethodError\",\"failed_at\":1635462070.8818843,\"retry_count\":25,\"retried_at\":1637377445.9415011}">]
```

**Comment by corylown** [comment]
When I try processing the Aggregator generated full MARC21 dump from Princeton I get this error:

```
2022-03-24T19:24:59.229Z pid=37465 tid=1c75 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"MarcProfilingJob","args":[{"job_class":"MarcProfilingJob","job_id":"fb4d8652-840a-4de8-8493-25240fb2c771","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[{"_aj_globalid":"gid://aggregator/ActiveStorage::Blob/531"},{"count":6601733,"_aj_ruby2_keywords":["count"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2022-03-24T18:26:47Z"}],"jid":"03cb2a8251e8bc9bc251b7ba","created_at":1648146407.03695,"enqueued_at":1648146407.037004},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"MarcProfilingJob\",\"args\":[{\"job_class\":\"MarcProfilingJob\",\"job_id\":\"fb4d8652-840a-4de8-8493-25240fb2c771\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://aggregator/ActiveStorage::Blob/531\"},{\"count\":6601733,\"_aj_ruby2_keywords\":[\"count\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2022-03-24T18:26:47Z\"}],\"jid\":\"03cb2a8251e8bc9bc251b7ba\",\"created_at\":1648146407.03695,\"enqueued_at\":1648146407.037004}"}
2022-03-24T19:24:59.267Z pid=37465 tid=1c75 WARN: NoMethodError: undefined method `pack' for nil:NilClass
2022-03-24T19:24:59.268Z pid=37465 tid=1c75 WARN: /Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:364:in `block in decode'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:339:in `upto'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:339:in `decode'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:283:in `decode'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:233:in `block in each'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:273:in `each_raw'
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:232:in `each'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:90:in `each_with_index'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:90:in `each_raw_record'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:102:in `each'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:102:in `each'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:102:in `each'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:102:in `each_combined_record'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:80:in `block in each'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:196:in `block (2 levels) in with_reader'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:275:in `with_honeybadger_context'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:195:in `block in with_reader'
/Users/corylown/.gem/ruby/3.0.3/gems/activestorage-7.0.2.3/lib/active_storage/downloader.rb:15:in `block in open'
/Users/corylown/.gem/ruby/3.0.3/gems/activestorage-7.0.2.3/lib/active_storage/downloader.rb:24:in `open_tempfile'
/Users/corylown/.gem/ruby/3.0.3/gems/activestorage-7.0.2.3/lib/active_storage/downloader.rb:12:in `open'
/Users/corylown/.gem/ruby/3.0.3/gems/activestorage-7.0.2.3/lib/active_storage/service.rb:90:in `open'
/Users/corylown/.gem/ruby/3.0.3/gems/activestorage-7.0.2.3/app/models/active_storage/blob.rb:301:in `open'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:194:in `with_reader'
/Users/corylown/workspace/pod4lib/aggregator/app/services/marc_record_service.rb:78:in `each'
/Users/corylown/workspace/pod4lib/aggregator/app/jobs/marc_profiling_job.rb:48:in `each_slice'
/Users/corylown/workspace/pod4lib/aggregator/app/jobs/marc_profiling_job.rb:48:in `perform'
```

**Comment by corylown** [comment]
Record/File with possible invalid UTF-8 byte sequence in field tag:

```
[#<MarcRecord:0x0000000006f7ecb0
  id: 270092133,
  file_id: 6251,
  upload_id: 3666,
  marc001: "9956296563506421",
  bytecount: nil,
  length: nil,
  index: 44754,
  checksum: "b77b97f155419d134dc5ef711dd220b2",
  status: "delete",
  json: nil>] 
```

**Comment by corylown** [comment]
Record was submitted as part of `pod_fulldump_6423467350006421_20210130_140137[052]_new_105.xml.gz` at `16 Mar 15:36`. Note the invalid marc tag here: `<marc:datafield tag="�xo" ind1=" " ind2=" ">`

```
  <marc:record>
    <marc:leader>01278dgm a2200373Ka 4500</marc:leader>
    <marc:controlfield tag="001">9956296563506421</marc:controlfield>
    <marc:controlfield tag="005">20100913080713.0</marc:controlfield>
    <marc:controlfield tag="007">vd dvaiz|</marc:controlfield>
    <marc:controlfield tag="008">081213s2007    ag 066            vlspa d</marc:controlfield>
    <marc:datafield tag="035" ind1=" " ind2=" ">
      <marc:subfield code="a">(OCoLC)ocn282919136</marc:subfield>
      <marc:subfield code="0">(uri) http://www.worldcat.org/oclc/282919136</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="035" ind1=" " ind2=" ">
      <marc:subfield code="a">(OCoLC)282919136</marc:subfield>
      <marc:subfield code="0">(uri) http://www.worldcat.org/oclc/282919136</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="035" ind1=" " ind2=" ">
      <marc:subfield code="a">(NjP)5629656-princetondb</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="040" ind1=" " ind2=" ">
      <marc:subfield code="a">GZM</marc:subfield>
      <marc:subfield code="c">GZM</marc:subfield>
      <marc:subfield code="d">GZM</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="043" ind1=" " ind2=" ">
      <marc:subfield code="a">s-bo---</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="090" ind1=" " ind2=" ">
      <marc:subfield code="a">PQ7809</marc:subfield>
      <marc:subfield code="b">.Y47 2007</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="245" ind1="0" ind2="0">
      <marc:subfield code="a">Yerba Mala /</marc:subfield>
      <marc:subfield code="c">Colectivo 7 presenta.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="260" ind1=" " ind2=" ">
      <marc:subfield code="a">[Argentina? :</marc:subfield>
      <marc:subfield code="b">Editorial Yerba Mala Cartonera,</marc:subfield>
      <marc:subfield code="c">2007]</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="300" ind1=" " ind2=" ">
      <marc:subfield code="a">1 videodisc (ca. 66 min.) :</marc:subfield>
      <marc:subfield code="b">sd., col. ;</marc:subfield>
      <marc:subfield code="c">4 3/4 in.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="�xo" ind1=" " ind2=" ">
      <marc:subfield code="a">Latin American and Iberian videos in Princeton University Library</marc:subfield>
      <marc:subfield code="5">NjP</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="538" ind1=" " ind2=" ">
      <marc:subfield code="a">DVD-R.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="500" ind1=" " ind2=" ">
      <marc:subfield code="a">Title taken from DVD container.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="650" ind1=" " ind2="0">
      <marc:subfield code="a">Bolivian literature</marc:subfield>
      <marc:subfield code="y">21st century</marc:subfield>
      <marc:subfield code="x">History and criticism.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="610" ind1="2" ind2="0">
      <marc:subfield code="a">Yerba Mala Cartonera.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="650" ind1=" " ind2="0">
      <marc:subfield code="a">Small presses</marc:subfield>
      <marc:subfield code="z">Bolivia.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="650" ind1=" " ind2="0">
      <marc:subfield code="a">Refuse collectors</marc:subfield>
      <marc:subfield code="z">Bolivia.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="650" ind1=" " ind2="0">
      <marc:subfield code="a">Paperboard</marc:subfield>
      <marc:subfield code="x">Recycling</marc:subfield>
      <marc:subfield code="z">Bolivia.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="650" ind1=" " ind2="0">
      <marc:subfield code="a">Artists' books</marc:subfield>
      <marc:subfield code="z">Bolivia.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="651" ind1=" " ind2="0">
      <marc:subfield code="a">La Paz (Bolivia)</marc:subfield>
      <marc:subfield code="x">Social life and customs.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="651" ind1=" " ind2="0">
      <marc:subfield code="a">El Alto (Bolivia)</marc:subfield>
      <marc:subfield code="x">Social life and customs.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="650" ind1=" " ind2="0">
      <marc:subfield code="a">Documentary films.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="710" ind1="2" ind2=" ">
      <marc:subfield code="a">Colectivo 7.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="710" ind1="2" ind2=" ">
      <marc:subfield code="a">Yerba Mala Cartonera.</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="994" ind1=" " ind2=" ">
      <marc:subfield code="a">Z0</marc:subfield>
      <marc:subfield code="b">PUL</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="948" ind1=" " ind2=" ">
      <marc:subfield code="h">NO HOLDINGS IN PUL - 1 OTHER HOLDINGS</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="904" ind1=" " ind2=" ">
      <marc:subfield code="a">ldm</marc:subfield>
      <marc:subfield code="b">o</marc:subfield>
      <marc:subfield code="h">m</marc:subfield>
      <marc:subfield code="c">v</marc:subfield>
      <marc:subfield code="e">20081223</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="852" ind1="0" ind2=" ">
      <marc:subfield code="b">firestone</marc:subfield>
      <marc:subfield code="c">vidl</marc:subfield>
      <marc:subfield code="8">22174516150006421</marc:subfield>
    </marc:datafield>
    <marc:datafield tag="952" ind1=" " ind2=" ">
      <marc:subfield code="a">2020-12-02 19:24:16</marc:subfield>
      <marc:subfield code="8">22174516150006421</marc:subfield>
      <marc:subfield code="b">Firestone Library</marc:subfield>
      <marc:subfield code="c">vidl Firestone Circ Desk</marc:subfield>
      <marc:subfield code="e">false</marc:subfield>
    </marc:datafield>
  </marc:record>
```

**Comment by corylown** [comment]
ruby-marc error when trying to read broken marc21 file:

```
irb(main):027:0> file = File.open(path)
=> #<File:/Users/corylown/Desktop/pod-problem-files/Princeton/bad-records-296/AAAmsplit00006857.mrc>
irb(main):028:0> reader = MARC::Reader.new(file, external_encoding: 'UTF-8')
=> 
#<MARC::Reader:0x00007fc62c410ec0                                               
...                                                                             
irb(main):029:0> reader.each { |rec| rec['001'] }
/Users/corylown/.gem/ruby/3.0.3/gems/marc-1.1.1/lib/marc/reader.rb:364:in `block in decode': undefined method `pack' for nil:NilClass (NoMethodError)  
```

**Comment by corylown** [comment]
I don't think there's a bug here to fix. The file is not parse-able as MARC. The job status design re-working as part of #317  should help clarify the meaning of the job status.
